Update index.js
The update of dependency "ipaddr.js": "1.1.0" cause "TypeError: ip.toIPv4Address is not a function" since class ipaddr.IPv4 doesn't have function toIPv4Address anymore